#!/bin/bash

./generate A4 landscape > A4_Landscape_ISO7200_DE.svg;
./generate A4 portrait > A4_Portrait_ISO7200_DE.svg;
for i in A3 A2 A1 A0; do
    ./generate $i landscape > ${i}_Landscape_ISO7200_DE.svg;
done
